Change: Allow multiple #<issue>s without additional prefixes.
OpenTTD/OpenTTD-git-hooks pull request #9
Opened 2019-02-02 16:26 UTC by PeterN

Allow commits in the form "Fix #<issue1>, #<issue2>: "

2019-02-18 23:41 UTC, michicc approved these changes

2019-02-18 23:56 UTC, glx22 requested changes

2019-02-18 23:56 UTC, glx22 commented on hooks/check-message.py
>  *** First line of message must match: '<keyword>( #<issue>| <commit>(, (<keyword> #<issue>|<commit>))*)?: ([<section])? <Details>'
Update comments

2020-01-23 18:53 UTC, glx22 commented on hooks/check-message.py
>  *** First line of message must match: '<keyword>( #<issue>| <commit>(, (<keyword> #<issue>|<commit>))*)?: ([<section])? <Details>'
```suggestion
*** First line of message must match: '<keyword>( #<issue>| <commit>(, ([<keyword> ]#<issue>|<commit>))*)?: ([<section>])? <Details>'
```

2021-04-06 21:48 UTC, closed without merging